In [1]:
import numpy as np

## Creating Arrays

In [2]:
arr1=np.array([1,2,3])
arr2=np.array((4,5,6))
arr3=np.array([[1,2],[3,4]])
arr4=np.array([True,False,True])
print(arr1,arr2,arr3,arr4)

[1 2 3] [4 5 6] [[1 2]
 [3 4]] [ True False  True]


## Array Dimensions

In [3]:
print(np.array([1,2,3]).ndim)
print(np.array([[1,2],[3,4]]).ndim)
print(np.array([[[1],[2]],[[3],[4]]]).ndim)
print(np.array([[[[1]]]]).ndim)

1
2
3
4


## Shape & Reshape

In [55]:
a=np.arange(6)
print(a.shape)
print(a.reshape(2,3))
print(a.reshape(3,2))
print(a.reshape(1,6))
print(a.reshape(1,4))

(6,)
[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]
[[0 1 2 3 4 5]]


ValueError: cannot reshape array of size 6 into shape (1,4)

## Data Types

In [54]:
print(np.array([1,2,3]).dtype)
print(np.array([1.1,2.2]).dtype)
print(np.array([1,2,3],dtype=float).dtype)
print(np.array(['ABVFJDDH','BCJ']).dtype)

int64
float64
float64
<U8


## Arithmetic Operations

In [6]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


## Comparison Operations

In [7]:
a=np.array([10,20,30])
print(a>15)
print(a==20)
print(a!=20)
print(a<=20)

[False  True  True]
[False  True False]
[ True False  True]
[ True  True False]


## Broadcasting

In [8]:
a=np.array([1,2,3])
print(a+10)
print(a*5)
print(a+[10,20,30])
print(np.array([[1],[2],[3]])+np.array([10,20]))

[11 12 13]
[ 5 10 15]
[11 22 33]
[[11 21]
 [12 22]
 [13 23]]


## zeros ones full

In [10]:
print(np.zeros((2,2)))
print(np.ones((2,2)))
print(np.full((2,2),9))
print(np.eye(3))

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[9 9]
 [9 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## arange & linspace

In [11]:
print(np.arange(1,10))
print(np.arange(1,10,2))
print(np.linspace(0,1,5))
print(np.linspace(10,20,4))

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[0.   0.25 0.5  0.75 1.  ]
[10.         13.33333333 16.66666667 20.        ]


## Random

In [12]:
print(np.random.randint(1,10,5))
print(np.random.rand(3))
print(np.random.randn(3))
print(np.random.choice([10,20,30],5))

[5 5 1 9 1]
[0.70773097 0.45922469 0.18750023]
[-0.99432473  1.23631717 -1.03353794]
[10 10 30 10 10]


## Mathematical Functions

In [13]:
arr=np.array([10,20,30,40])
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

100
10
40
25.0
25.0
11.180339887498949
125.0


## Dot Product

In [14]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.dot(a,b))
print(a@b)

32
32


## Matrix Multiplication

In [15]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.matmul(a,b))
print(a@b)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


## Sorting & Searching

In [16]:
arr=np.array([40,10,30,20])
print(np.sort(arr))
print(np.argsort(arr))
print(np.where(arr==30))
print(np.searchsorted(np.sort(arr),25))

[10 20 30 40]
[1 3 2 0]
(array([2]),)
2


## Stacking & Splitting

In [17]:
a=np.array([1,2])
b=np.array([3,4])
print(np.vstack((a,b)))
print(np.hstack((a,b)))
arr=np.array([1,2,3,4,5,6])
print(np.split(arr,3))

[[1 2]
 [3 4]]
[1 2 3 4]
[array([1, 2]), array([3, 4]), array([5, 6])]


## Linear Algebra

In [18]:
a=np.array([[1,2],[3,4]])
print(np.linalg.inv(a))
print(np.linalg.det(a))
vals,vecs=np.linalg.eig(a)
print(vals)
print(vecs)

[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


## Pandas

In [19]:
import pandas as pd

## Series

In [20]:
s=pd.Series([10,20,30])
print(s)
print(s[0])
print(s[1:])
print(s.mean())

0    10
1    20
2    30
dtype: int64
10
1    20
2    30
dtype: int64
20.0


## Creating DataFrames

In [21]:
df=pd.DataFrame({'Name':['A','B'],'Age':[20,25]})
print(df)
print(df.columns)
print(df.shape)
print(df.head())

  Name  Age
0    A   20
1    B   25
Index(['Name', 'Age'], dtype='object')
(2, 2)
  Name  Age
0    A   20
1    B   25


## Reading Data

In [24]:
df1 = pd.read_csv('data.csv')
df2 = pd.read_excel('data.xlsx')
df3 = pd.read_json('data.json')

## Writing Data

In [22]:
df.to_csv('data.csv')
df.to_excel('data.xlsx')
df.to_json('data.json')

## Info & Shape

In [25]:
df=pd.DataFrame({'Name':['A','B'],'Age':[20,25]})
df.info()
print(df.shape)
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    2 non-null      object
 1   Age     2 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 160.0+ bytes
(2, 2)
             Age
count   2.000000
mean   22.500000
std     3.535534
min    20.000000
25%    21.250000
50%    22.500000
75%    23.750000
max    25.000000


## loc & iloc

In [46]:
df=pd.DataFrame({'Name':['A','B','C'],'Age':[20,25,30]})
print(df.loc[0])
print(df.loc[:,['Name']])
print(df.iloc[1])
print(df.iloc[:2])

Name     A
Age     20
Name: 0, dtype: object
  Name
0    A
1    B
2    C
Name     B
Age     25
Name: 1, dtype: object
  Name  Age
0    A   20
1    B   25


In [47]:
df.index = [101,102,103]
print(df)

    Name  Age
101    A   20
102    B   25
103    C   30


In [48]:
df.loc[102]

Name     B
Age     25
Name: 102, dtype: object

In [50]:
df.loc[1]

KeyError: 1

In [49]:
df.iloc[1]

Name     B
Age     25
Name: 102, dtype: object

## Boolean Filtering

In [27]:
df=pd.DataFrame({'Age':[20,25,30,35]})
print(df[df['Age']>25])
print(df[df['Age']==30])

   Age
2   30
3   35
   Age
2   30


## Query Method

In [28]:
df=pd.DataFrame({'Age':[20,25,30,35]})
print(df.query('Age>25'))
print(df.query('Age==30'))

   Age
2   30
3   35
   Age
2   30


## Missing Values

In [29]:
df=pd.DataFrame({'A':[1,None,3]})
print(df.isnull())
print(df.notnull())
print(df.fillna(0))
print(df.dropna())

       A
0  False
1   True
2  False
       A
0   True
1  False
2   True
     A
0  1.0
1  0.0
2  3.0
     A
0  1.0
2  3.0


## Duplicates

In [30]:
df=pd.DataFrame({'A':[1,1,2,2]})
print(df.duplicated())
print(df.drop_duplicates())

0    False
1     True
2    False
3     True
dtype: bool
   A
0  1
2  2


## Rename Columns

In [31]:
df=pd.DataFrame({'Age':[20,25]})
print(df.rename(columns={'Age':'Student_Age'}))

   Student_Age
0           20
1           25


## Change Data Types

In [32]:
df=pd.DataFrame({'Age':['20','25']})
print(df.dtypes)
df['Age']=df['Age'].astype(int)
print(df.dtypes)

Age    object
dtype: object
Age    int64
dtype: object


## Replace Values

In [33]:
df=pd.DataFrame({'City':['Pune','Mumbai','Pune']})
print(df.replace('Pune','Nashik'))

     City
0  Nashik
1  Mumbai
2  Nashik


## get_dummies

In [35]:
df=pd.DataFrame({'City':['Pune','Mumbai','Delhi']})
print(pd.get_dummies(df['City']))

   Delhi  Mumbai  Pune
0      0       0     1
1      0       1     0
2      1       0     0


## Sorting & Ranking

In [36]:
df=pd.DataFrame({'Marks':[50,80,70]})
print(df.sort_values('Marks'))
df['Rank']=df['Marks'].rank(ascending=False)
print(df)

   Marks
0     50
2     70
1     80
   Marks  Rank
0     50   3.0
1     80   1.0
2     70   2.0


## GroupBy

In [37]:
df=pd.DataFrame({'City':['Pune','Pune','Mumbai'],'Sales':[100,200,300]})
print(df.groupby('City')['Sales'].sum())
print(df.groupby('City')['Sales'].mean())

City
Mumbai    300
Pune      300
Name: Sales, dtype: int64
City
Mumbai    300.0
Pune      150.0
Name: Sales, dtype: float64


## Pivot Tables

In [39]:
df=pd.DataFrame({'City':['Pune','Pune','Mumbai'],'Sales':[100,200,300]})
print(pd.pivot_table(df,values='Sales',index='City',aggfunc='sum'))

        Sales
City         
Mumbai    300
Pune      300


## Date & Time

In [43]:
dates=pd.DataFrame({'Date':['2025-01-01','2025-02-01']})
dates['Date']=pd.to_datetime(dates['Date'])
print(dates['Date'].dt.year)
print(dates['Date'].dt.month)

0    2025
1    2025
Name: Date, dtype: int64
0    1
1    2
Name: Date, dtype: int64


## String Operations

In [44]:
s=pd.Series(['Alice','Bob','Charlie'])
print(s.str.upper())
print(s.str.lower())
print(s.str.contains('a',case=False))
print(s.str.len())

0      ALICE
1        BOB
2    CHARLIE
dtype: object
0      alice
1        bob
2    charlie
dtype: object
0     True
1    False
2     True
dtype: bool
0    5
1    3
2    7
dtype: int64
